### ISSUE TITLE
Error on integrating Vaadin Player 3.0.1 with java 8 

### ISSUE THREAD

**Issue by codevector** [parttio/VaadinAudioPlayer#5]
We are getting the following exceptions on integrating Vaadin Player 3.0.1 with Java 8 ( during running it ). 

Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at org.vaadin.addon.audio.server.encoders.WaveEncoder.encode(WaveEncoder.java:45)
        at org.vaadin.addon.audio.server.Stream.getChunkData(Stream.java:227)
        at org.vaadin.addon.audio.server.AudioPlayer.lambda$registerChunkResource$46a38a13$1(AudioPlayer.java:210)
        at com.vaadin.flow.server.communication.StreamResourceHandler.handleRequest(StreamResourceHandler.java:89)
        at com.vaadin.flow.server.communication.StreamRequestHandler.handleRequest(StreamRequestHandler.java:106)
        at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1570)
   

It might be an issue with compiling vaadin player 3.0.1 code with > JDK8.

Plz look into https://github.com/eclipse/jetty.project/issues/3244

**Comment by jcgueriaud1** [comment]
The 3.0.2 has been released and built with Java 8
